// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize a new game with player configuration.
///
/// Combines character generation and world initialization into a single call.
/// Returns the initial game state snapshot for UI rendering.
///
/// # Arguments
/// * `seed` - World seed for deterministic generation
/// * `config` - Player configuration (name, archetype, difficulty, etc.)
ApiSimpleGameState? engineNewGame(
        {required BigInt seed, required ApiPlayerConfig config}) =>
    RustLib.instance.api.crateApiEngineNewGame(seed: seed, config: config);

/// Advance simulation by specified ticks and return updated state.
///
/// This is the main game loop function Flutter should call to progress time.
///
/// # Arguments
/// * `ticks` - Number of ticks to advance
ApiSimpleGameState? engineStep({required int ticks}) =>
    RustLib.instance.api.crateApiEngineStep(ticks: ticks);

/// Tick the engine by 1 tick (convenience wrapper).
void engineTick() => RustLib.instance.api.crateApiEngineTick();

/// Advance the simulation by multiple ticks (convenience wrapper).
///
/// # Arguments
/// * `count` - Number of ticks to advance
void engineTickMany({required int count}) =>
    RustLib.instance.api.crateApiEngineTickMany(count: count);

/// Make a choice in the current event and advance simulation.
///
/// Applies the choice outcome and progresses time by the specified ticks.
///
/// # Arguments
/// * `storylet_id` - ID of the current storylet/event
/// * `choice_id` - ID of the selected choice
/// * `ticks` - Number of ticks to advance after applying the choice
ApiSimpleGameState? engineChooseOption(
        {required String storyletId,
        required String choiceId,
        required int ticks}) =>
    RustLib.instance.api.crateApiEngineChooseOption(
        storyletId: storyletId, choiceId: choiceId, ticks: ticks);

/// Get current storylet/event card for UI display.
///
/// Returns the next eligible storylet, or None if no events are available.
ApiDirectorEventView? getCurrentStorylet() =>
    RustLib.instance.api.crateApiGetCurrentStorylet();

/// Get available choices for the current event.
///
/// Returns empty vector if no event is active.
List<ApiDirectorChoiceView> getAvailableChoices() =>
    RustLib.instance.api.crateApiGetAvailableChoices();

/// Get unified game state snapshot for UI.
///
/// This is the primary comprehensive state accessor Flutter should use
/// for full UI rendering (includes narrative heat, karma bands, etc.).
ApiGameStateSnapshot? getGameStateSnapshot() =>
    RustLib.instance.api.crateApiGetGameStateSnapshot();
