// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiDirectorChoiceView dco_decode_api_director_choice_view(dynamic raw);

  @protected
  ApiDirectorEventView dco_decode_api_director_event_view(dynamic raw);

  @protected
  ApiGameStateSnapshot dco_decode_api_game_state_snapshot(dynamic raw);

  @protected
  ApiLifeStageInfo dco_decode_api_life_stage_info(dynamic raw);

  @protected
  ApiPlayerConfig dco_decode_api_player_config(dynamic raw);

  @protected
  ApiRelationship dco_decode_api_relationship(dynamic raw);

  @protected
  ApiRelationshipSnapshot dco_decode_api_relationship_snapshot(dynamic raw);

  @protected
  ApiSimpleGameState dco_decode_api_simple_game_state(dynamic raw);

  @protected
  ApiSimpleRelationship dco_decode_api_simple_relationship(dynamic raw);

  @protected
  ApiStat dco_decode_api_stat(dynamic raw);

  @protected
  ApiStatsSnapshot dco_decode_api_stats_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiDirectorEventView dco_decode_box_autoadd_api_director_event_view(
      dynamic raw);

  @protected
  ApiGameStateSnapshot dco_decode_box_autoadd_api_game_state_snapshot(
      dynamic raw);

  @protected
  ApiPlayerConfig dco_decode_box_autoadd_api_player_config(dynamic raw);

  @protected
  ApiSimpleGameState dco_decode_box_autoadd_api_simple_game_state(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ApiDirectorChoiceView> dco_decode_list_api_director_choice_view(
      dynamic raw);

  @protected
  List<ApiRelationship> dco_decode_list_api_relationship(dynamic raw);

  @protected
  List<ApiSimpleRelationship> dco_decode_list_api_simple_relationship(
      dynamic raw);

  @protected
  List<ApiStat> dco_decode_list_api_stat(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiDirectorEventView? dco_decode_opt_box_autoadd_api_director_event_view(
      dynamic raw);

  @protected
  ApiGameStateSnapshot? dco_decode_opt_box_autoadd_api_game_state_snapshot(
      dynamic raw);

  @protected
  ApiSimpleGameState? dco_decode_opt_box_autoadd_api_simple_game_state(
      dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiDirectorChoiceView sse_decode_api_director_choice_view(
      SseDeserializer deserializer);

  @protected
  ApiDirectorEventView sse_decode_api_director_event_view(
      SseDeserializer deserializer);

  @protected
  ApiGameStateSnapshot sse_decode_api_game_state_snapshot(
      SseDeserializer deserializer);

  @protected
  ApiLifeStageInfo sse_decode_api_life_stage_info(SseDeserializer deserializer);

  @protected
  ApiPlayerConfig sse_decode_api_player_config(SseDeserializer deserializer);

  @protected
  ApiRelationship sse_decode_api_relationship(SseDeserializer deserializer);

  @protected
  ApiRelationshipSnapshot sse_decode_api_relationship_snapshot(
      SseDeserializer deserializer);

  @protected
  ApiSimpleGameState sse_decode_api_simple_game_state(
      SseDeserializer deserializer);

  @protected
  ApiSimpleRelationship sse_decode_api_simple_relationship(
      SseDeserializer deserializer);

  @protected
  ApiStat sse_decode_api_stat(SseDeserializer deserializer);

  @protected
  ApiStatsSnapshot sse_decode_api_stats_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiDirectorEventView sse_decode_box_autoadd_api_director_event_view(
      SseDeserializer deserializer);

  @protected
  ApiGameStateSnapshot sse_decode_box_autoadd_api_game_state_snapshot(
      SseDeserializer deserializer);

  @protected
  ApiPlayerConfig sse_decode_box_autoadd_api_player_config(
      SseDeserializer deserializer);

  @protected
  ApiSimpleGameState sse_decode_box_autoadd_api_simple_game_state(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ApiDirectorChoiceView> sse_decode_list_api_director_choice_view(
      SseDeserializer deserializer);

  @protected
  List<ApiRelationship> sse_decode_list_api_relationship(
      SseDeserializer deserializer);

  @protected
  List<ApiSimpleRelationship> sse_decode_list_api_simple_relationship(
      SseDeserializer deserializer);

  @protected
  List<ApiStat> sse_decode_list_api_stat(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiDirectorEventView? sse_decode_opt_box_autoadd_api_director_event_view(
      SseDeserializer deserializer);

  @protected
  ApiGameStateSnapshot? sse_decode_opt_box_autoadd_api_game_state_snapshot(
      SseDeserializer deserializer);

  @protected
  ApiSimpleGameState? sse_decode_opt_box_autoadd_api_simple_game_state(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_director_choice_view(
      ApiDirectorChoiceView self, SseSerializer serializer);

  @protected
  void sse_encode_api_director_event_view(
      ApiDirectorEventView self, SseSerializer serializer);

  @protected
  void sse_encode_api_game_state_snapshot(
      ApiGameStateSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_api_life_stage_info(
      ApiLifeStageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_player_config(
      ApiPlayerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_api_relationship(
      ApiRelationship self, SseSerializer serializer);

  @protected
  void sse_encode_api_relationship_snapshot(
      ApiRelationshipSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_api_simple_game_state(
      ApiSimpleGameState self, SseSerializer serializer);

  @protected
  void sse_encode_api_simple_relationship(
      ApiSimpleRelationship self, SseSerializer serializer);

  @protected
  void sse_encode_api_stat(ApiStat self, SseSerializer serializer);

  @protected
  void sse_encode_api_stats_snapshot(
      ApiStatsSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_director_event_view(
      ApiDirectorEventView self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_game_state_snapshot(
      ApiGameStateSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_player_config(
      ApiPlayerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_simple_game_state(
      ApiSimpleGameState self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_director_choice_view(
      List<ApiDirectorChoiceView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_relationship(
      List<ApiRelationship> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_simple_relationship(
      List<ApiSimpleRelationship> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_stat(List<ApiStat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_director_event_view(
      ApiDirectorEventView? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_game_state_snapshot(
      ApiGameStateSnapshot? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_simple_game_state(
      ApiSimpleGameState? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
