// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 905038409;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'syn_api',
    ioDirectory: '../rust/syn_api/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  ApiSimpleGameState? crateApiEngineChooseOption(
      {required String storyletId,
      required String choiceId,
      required int ticks});

  ApiSimpleGameState? crateApiEngineNewGame(
      {required BigInt seed, required ApiPlayerConfig config});

  ApiSimpleGameState? crateApiEngineStep({required int ticks});

  void crateApiEngineTick();

  void crateApiEngineTickMany({required int count});

  List<ApiDirectorChoiceView> crateApiGetAvailableChoices();

  ApiDirectorEventView? crateApiGetCurrentStorylet();

  ApiGameStateSnapshot? crateApiGetGameStateSnapshot();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ApiSimpleGameState? crateApiEngineChooseOption(
      {required String storyletId,
      required String choiceId,
      required int ticks}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(storyletId, serializer);
        sse_encode_String(choiceId, serializer);
        sse_encode_u_32(ticks, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_api_simple_game_state,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineChooseOptionConstMeta,
      argValues: [storyletId, choiceId, ticks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineChooseOptionConstMeta => const TaskConstMeta(
        debugName: "engine_choose_option",
        argNames: ["storyletId", "choiceId", "ticks"],
      );

  @override
  ApiSimpleGameState? crateApiEngineNewGame(
      {required BigInt seed, required ApiPlayerConfig config}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(seed, serializer);
        sse_encode_box_autoadd_api_player_config(config, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_api_simple_game_state,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineNewGameConstMeta,
      argValues: [seed, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineNewGameConstMeta => const TaskConstMeta(
        debugName: "engine_new_game",
        argNames: ["seed", "config"],
      );

  @override
  ApiSimpleGameState? crateApiEngineStep({required int ticks}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(ticks, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_api_simple_game_state,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineStepConstMeta,
      argValues: [ticks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineStepConstMeta => const TaskConstMeta(
        debugName: "engine_step",
        argNames: ["ticks"],
      );

  @override
  void crateApiEngineTick() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineTickConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineTickConstMeta => const TaskConstMeta(
        debugName: "engine_tick",
        argNames: [],
      );

  @override
  void crateApiEngineTickMany({required int count}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(count, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEngineTickManyConstMeta,
      argValues: [count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineTickManyConstMeta => const TaskConstMeta(
        debugName: "engine_tick_many",
        argNames: ["count"],
      );

  @override
  List<ApiDirectorChoiceView> crateApiGetAvailableChoices() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_api_director_choice_view,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetAvailableChoicesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAvailableChoicesConstMeta =>
      const TaskConstMeta(
        debugName: "get_available_choices",
        argNames: [],
      );

  @override
  ApiDirectorEventView? crateApiGetCurrentStorylet() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_api_director_event_view,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetCurrentStoryletConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCurrentStoryletConstMeta => const TaskConstMeta(
        debugName: "get_current_storylet",
        argNames: [],
      );

  @override
  ApiGameStateSnapshot? crateApiGetGameStateSnapshot() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_api_game_state_snapshot,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetGameStateSnapshotConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetGameStateSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "get_game_state_snapshot",
        argNames: [],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiDirectorChoiceView dco_decode_api_director_choice_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiDirectorChoiceView(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApiDirectorEventView dco_decode_api_director_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiDirectorEventView(
      storyletId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      choices: dco_decode_list_api_director_choice_view(arr[2]),
    );
  }

  @protected
  ApiGameStateSnapshot dco_decode_api_game_state_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ApiGameStateSnapshot(
      currentTick: dco_decode_u_64(arr[0]),
      playerAgeYears: dco_decode_u_32(arr[1]),
      lifeStage: dco_decode_String(arr[2]),
      stats: dco_decode_api_stats_snapshot(arr[3]),
      relationships: dco_decode_api_relationship_snapshot(arr[4]),
      narrativeHeat: dco_decode_f_32(arr[5]),
      heatLevel: dco_decode_String(arr[6]),
      heatTrend: dco_decode_f_32(arr[7]),
      currentEvent: dco_decode_opt_box_autoadd_api_director_event_view(arr[8]),
      karma: dco_decode_f_32(arr[9]),
      karmaBand: dco_decode_String(arr[10]),
      moodBand: dco_decode_String(arr[11]),
      lifeStageInfo: dco_decode_api_life_stage_info(arr[12]),
    );
  }

  @protected
  ApiLifeStageInfo dco_decode_api_life_stage_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApiLifeStageInfo(
      lifeStage: dco_decode_String(arr[0]),
      playerAgeYears: dco_decode_i_32(arr[1]),
      showWealth: dco_decode_bool(arr[2]),
      showReputation: dco_decode_bool(arr[3]),
      showWisdom: dco_decode_bool(arr[4]),
      showKarma: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ApiPlayerConfig dco_decode_api_player_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiPlayerConfig(
      name: dco_decode_String(arr[0]),
      pronouns: dco_decode_opt_String(arr[1]),
      archetype: dco_decode_String(arr[2]),
      difficulty: dco_decode_String(arr[3]),
      sfwMode: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ApiRelationship dco_decode_api_relationship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ApiRelationship(
      actorId: dco_decode_i_64(arr[0]),
      targetId: dco_decode_i_64(arr[1]),
      affection: dco_decode_f_32(arr[2]),
      trust: dco_decode_f_32(arr[3]),
      attraction: dco_decode_f_32(arr[4]),
      familiarity: dco_decode_f_32(arr[5]),
      resentment: dco_decode_f_32(arr[6]),
      affectionBand: dco_decode_String(arr[7]),
      trustBand: dco_decode_String(arr[8]),
      attractionBand: dco_decode_String(arr[9]),
      resentmentBand: dco_decode_String(arr[10]),
      roleLabel: dco_decode_String(arr[11]),
    );
  }

  @protected
  ApiRelationshipSnapshot dco_decode_api_relationship_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ApiRelationshipSnapshot(
      relationships: dco_decode_list_api_relationship(arr[0]),
    );
  }

  @protected
  ApiSimpleGameState dco_decode_api_simple_game_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ApiSimpleGameState(
      currentDay: dco_decode_u_32(arr[0]),
      currentTick: dco_decode_u_64(arr[1]),
      playerAge: dco_decode_u_32(arr[2]),
      lifeStage: dco_decode_String(arr[3]),
      stats: dco_decode_api_stats_snapshot(arr[4]),
      mood: dco_decode_String(arr[5]),
      karma: dco_decode_f_32(arr[6]),
      currentEvent: dco_decode_opt_box_autoadd_api_director_event_view(arr[7]),
      relationships: dco_decode_list_api_simple_relationship(arr[8]),
      recentMemories: dco_decode_list_String(arr[9]),
    );
  }

  @protected
  ApiSimpleRelationship dco_decode_api_simple_relationship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiSimpleRelationship(
      npcId: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      strength: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  ApiStat dco_decode_api_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiStat(
      kind: dco_decode_String(arr[0]),
      value: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  ApiStatsSnapshot dco_decode_api_stats_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiStatsSnapshot(
      stats: dco_decode_list_api_stat(arr[0]),
      moodBand: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApiDirectorEventView dco_decode_box_autoadd_api_director_event_view(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_director_event_view(raw);
  }

  @protected
  ApiGameStateSnapshot dco_decode_box_autoadd_api_game_state_snapshot(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_game_state_snapshot(raw);
  }

  @protected
  ApiPlayerConfig dco_decode_box_autoadd_api_player_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_player_config(raw);
  }

  @protected
  ApiSimpleGameState dco_decode_box_autoadd_api_simple_game_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_simple_game_state(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ApiDirectorChoiceView> dco_decode_list_api_director_choice_view(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_api_director_choice_view)
        .toList();
  }

  @protected
  List<ApiRelationship> dco_decode_list_api_relationship(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_relationship).toList();
  }

  @protected
  List<ApiSimpleRelationship> dco_decode_list_api_simple_relationship(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_api_simple_relationship)
        .toList();
  }

  @protected
  List<ApiStat> dco_decode_list_api_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_stat).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ApiDirectorEventView? dco_decode_opt_box_autoadd_api_director_event_view(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_api_director_event_view(raw);
  }

  @protected
  ApiGameStateSnapshot? dco_decode_opt_box_autoadd_api_game_state_snapshot(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_api_game_state_snapshot(raw);
  }

  @protected
  ApiSimpleGameState? dco_decode_opt_box_autoadd_api_simple_game_state(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_api_simple_game_state(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiDirectorChoiceView sse_decode_api_director_choice_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    return ApiDirectorChoiceView(id: var_id, label: var_label);
  }

  @protected
  ApiDirectorEventView sse_decode_api_director_event_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storyletId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_choices = sse_decode_list_api_director_choice_view(deserializer);
    return ApiDirectorEventView(
        storyletId: var_storyletId, title: var_title, choices: var_choices);
  }

  @protected
  ApiGameStateSnapshot sse_decode_api_game_state_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentTick = sse_decode_u_64(deserializer);
    var var_playerAgeYears = sse_decode_u_32(deserializer);
    var var_lifeStage = sse_decode_String(deserializer);
    var var_stats = sse_decode_api_stats_snapshot(deserializer);
    var var_relationships = sse_decode_api_relationship_snapshot(deserializer);
    var var_narrativeHeat = sse_decode_f_32(deserializer);
    var var_heatLevel = sse_decode_String(deserializer);
    var var_heatTrend = sse_decode_f_32(deserializer);
    var var_currentEvent =
        sse_decode_opt_box_autoadd_api_director_event_view(deserializer);
    var var_karma = sse_decode_f_32(deserializer);
    var var_karmaBand = sse_decode_String(deserializer);
    var var_moodBand = sse_decode_String(deserializer);
    var var_lifeStageInfo = sse_decode_api_life_stage_info(deserializer);
    return ApiGameStateSnapshot(
        currentTick: var_currentTick,
        playerAgeYears: var_playerAgeYears,
        lifeStage: var_lifeStage,
        stats: var_stats,
        relationships: var_relationships,
        narrativeHeat: var_narrativeHeat,
        heatLevel: var_heatLevel,
        heatTrend: var_heatTrend,
        currentEvent: var_currentEvent,
        karma: var_karma,
        karmaBand: var_karmaBand,
        moodBand: var_moodBand,
        lifeStageInfo: var_lifeStageInfo);
  }

  @protected
  ApiLifeStageInfo sse_decode_api_life_stage_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lifeStage = sse_decode_String(deserializer);
    var var_playerAgeYears = sse_decode_i_32(deserializer);
    var var_showWealth = sse_decode_bool(deserializer);
    var var_showReputation = sse_decode_bool(deserializer);
    var var_showWisdom = sse_decode_bool(deserializer);
    var var_showKarma = sse_decode_bool(deserializer);
    return ApiLifeStageInfo(
        lifeStage: var_lifeStage,
        playerAgeYears: var_playerAgeYears,
        showWealth: var_showWealth,
        showReputation: var_showReputation,
        showWisdom: var_showWisdom,
        showKarma: var_showKarma);
  }

  @protected
  ApiPlayerConfig sse_decode_api_player_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_pronouns = sse_decode_opt_String(deserializer);
    var var_archetype = sse_decode_String(deserializer);
    var var_difficulty = sse_decode_String(deserializer);
    var var_sfwMode = sse_decode_bool(deserializer);
    return ApiPlayerConfig(
        name: var_name,
        pronouns: var_pronouns,
        archetype: var_archetype,
        difficulty: var_difficulty,
        sfwMode: var_sfwMode);
  }

  @protected
  ApiRelationship sse_decode_api_relationship(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_actorId = sse_decode_i_64(deserializer);
    var var_targetId = sse_decode_i_64(deserializer);
    var var_affection = sse_decode_f_32(deserializer);
    var var_trust = sse_decode_f_32(deserializer);
    var var_attraction = sse_decode_f_32(deserializer);
    var var_familiarity = sse_decode_f_32(deserializer);
    var var_resentment = sse_decode_f_32(deserializer);
    var var_affectionBand = sse_decode_String(deserializer);
    var var_trustBand = sse_decode_String(deserializer);
    var var_attractionBand = sse_decode_String(deserializer);
    var var_resentmentBand = sse_decode_String(deserializer);
    var var_roleLabel = sse_decode_String(deserializer);
    return ApiRelationship(
        actorId: var_actorId,
        targetId: var_targetId,
        affection: var_affection,
        trust: var_trust,
        attraction: var_attraction,
        familiarity: var_familiarity,
        resentment: var_resentment,
        affectionBand: var_affectionBand,
        trustBand: var_trustBand,
        attractionBand: var_attractionBand,
        resentmentBand: var_resentmentBand,
        roleLabel: var_roleLabel);
  }

  @protected
  ApiRelationshipSnapshot sse_decode_api_relationship_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_relationships = sse_decode_list_api_relationship(deserializer);
    return ApiRelationshipSnapshot(relationships: var_relationships);
  }

  @protected
  ApiSimpleGameState sse_decode_api_simple_game_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentDay = sse_decode_u_32(deserializer);
    var var_currentTick = sse_decode_u_64(deserializer);
    var var_playerAge = sse_decode_u_32(deserializer);
    var var_lifeStage = sse_decode_String(deserializer);
    var var_stats = sse_decode_api_stats_snapshot(deserializer);
    var var_mood = sse_decode_String(deserializer);
    var var_karma = sse_decode_f_32(deserializer);
    var var_currentEvent =
        sse_decode_opt_box_autoadd_api_director_event_view(deserializer);
    var var_relationships =
        sse_decode_list_api_simple_relationship(deserializer);
    var var_recentMemories = sse_decode_list_String(deserializer);
    return ApiSimpleGameState(
        currentDay: var_currentDay,
        currentTick: var_currentTick,
        playerAge: var_playerAge,
        lifeStage: var_lifeStage,
        stats: var_stats,
        mood: var_mood,
        karma: var_karma,
        currentEvent: var_currentEvent,
        relationships: var_relationships,
        recentMemories: var_recentMemories);
  }

  @protected
  ApiSimpleRelationship sse_decode_api_simple_relationship(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_npcId = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_strength = sse_decode_f_32(deserializer);
    return ApiSimpleRelationship(
        npcId: var_npcId, name: var_name, strength: var_strength);
  }

  @protected
  ApiStat sse_decode_api_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_value = sse_decode_f_32(deserializer);
    return ApiStat(kind: var_kind, value: var_value);
  }

  @protected
  ApiStatsSnapshot sse_decode_api_stats_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stats = sse_decode_list_api_stat(deserializer);
    var var_moodBand = sse_decode_String(deserializer);
    return ApiStatsSnapshot(stats: var_stats, moodBand: var_moodBand);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApiDirectorEventView sse_decode_box_autoadd_api_director_event_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_director_event_view(deserializer));
  }

  @protected
  ApiGameStateSnapshot sse_decode_box_autoadd_api_game_state_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_game_state_snapshot(deserializer));
  }

  @protected
  ApiPlayerConfig sse_decode_box_autoadd_api_player_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_player_config(deserializer));
  }

  @protected
  ApiSimpleGameState sse_decode_box_autoadd_api_simple_game_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_simple_game_state(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiDirectorChoiceView> sse_decode_list_api_director_choice_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiDirectorChoiceView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_director_choice_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiRelationship> sse_decode_list_api_relationship(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiRelationship>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_relationship(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiSimpleRelationship> sse_decode_list_api_simple_relationship(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiSimpleRelationship>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_simple_relationship(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiStat> sse_decode_list_api_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiStat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_stat(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApiDirectorEventView? sse_decode_opt_box_autoadd_api_director_event_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_director_event_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApiGameStateSnapshot? sse_decode_opt_box_autoadd_api_game_state_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_game_state_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApiSimpleGameState? sse_decode_opt_box_autoadd_api_simple_game_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_api_simple_game_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_director_choice_view(
      ApiDirectorChoiceView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_api_director_event_view(
      ApiDirectorEventView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storyletId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_api_director_choice_view(self.choices, serializer);
  }

  @protected
  void sse_encode_api_game_state_snapshot(
      ApiGameStateSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.currentTick, serializer);
    sse_encode_u_32(self.playerAgeYears, serializer);
    sse_encode_String(self.lifeStage, serializer);
    sse_encode_api_stats_snapshot(self.stats, serializer);
    sse_encode_api_relationship_snapshot(self.relationships, serializer);
    sse_encode_f_32(self.narrativeHeat, serializer);
    sse_encode_String(self.heatLevel, serializer);
    sse_encode_f_32(self.heatTrend, serializer);
    sse_encode_opt_box_autoadd_api_director_event_view(
        self.currentEvent, serializer);
    sse_encode_f_32(self.karma, serializer);
    sse_encode_String(self.karmaBand, serializer);
    sse_encode_String(self.moodBand, serializer);
    sse_encode_api_life_stage_info(self.lifeStageInfo, serializer);
  }

  @protected
  void sse_encode_api_life_stage_info(
      ApiLifeStageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lifeStage, serializer);
    sse_encode_i_32(self.playerAgeYears, serializer);
    sse_encode_bool(self.showWealth, serializer);
    sse_encode_bool(self.showReputation, serializer);
    sse_encode_bool(self.showWisdom, serializer);
    sse_encode_bool(self.showKarma, serializer);
  }

  @protected
  void sse_encode_api_player_config(
      ApiPlayerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.pronouns, serializer);
    sse_encode_String(self.archetype, serializer);
    sse_encode_String(self.difficulty, serializer);
    sse_encode_bool(self.sfwMode, serializer);
  }

  @protected
  void sse_encode_api_relationship(
      ApiRelationship self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.actorId, serializer);
    sse_encode_i_64(self.targetId, serializer);
    sse_encode_f_32(self.affection, serializer);
    sse_encode_f_32(self.trust, serializer);
    sse_encode_f_32(self.attraction, serializer);
    sse_encode_f_32(self.familiarity, serializer);
    sse_encode_f_32(self.resentment, serializer);
    sse_encode_String(self.affectionBand, serializer);
    sse_encode_String(self.trustBand, serializer);
    sse_encode_String(self.attractionBand, serializer);
    sse_encode_String(self.resentmentBand, serializer);
    sse_encode_String(self.roleLabel, serializer);
  }

  @protected
  void sse_encode_api_relationship_snapshot(
      ApiRelationshipSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_api_relationship(self.relationships, serializer);
  }

  @protected
  void sse_encode_api_simple_game_state(
      ApiSimpleGameState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.currentDay, serializer);
    sse_encode_u_64(self.currentTick, serializer);
    sse_encode_u_32(self.playerAge, serializer);
    sse_encode_String(self.lifeStage, serializer);
    sse_encode_api_stats_snapshot(self.stats, serializer);
    sse_encode_String(self.mood, serializer);
    sse_encode_f_32(self.karma, serializer);
    sse_encode_opt_box_autoadd_api_director_event_view(
        self.currentEvent, serializer);
    sse_encode_list_api_simple_relationship(self.relationships, serializer);
    sse_encode_list_String(self.recentMemories, serializer);
  }

  @protected
  void sse_encode_api_simple_relationship(
      ApiSimpleRelationship self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.npcId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_f_32(self.strength, serializer);
  }

  @protected
  void sse_encode_api_stat(ApiStat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_f_32(self.value, serializer);
  }

  @protected
  void sse_encode_api_stats_snapshot(
      ApiStatsSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_api_stat(self.stats, serializer);
    sse_encode_String(self.moodBand, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_api_director_event_view(
      ApiDirectorEventView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_director_event_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_game_state_snapshot(
      ApiGameStateSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_game_state_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_player_config(
      ApiPlayerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_player_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_simple_game_state(
      ApiSimpleGameState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_simple_game_state(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_director_choice_view(
      List<ApiDirectorChoiceView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_director_choice_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_relationship(
      List<ApiRelationship> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_relationship(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_simple_relationship(
      List<ApiSimpleRelationship> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_simple_relationship(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_stat(List<ApiStat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_stat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_api_director_event_view(
      ApiDirectorEventView? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_director_event_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_api_game_state_snapshot(
      ApiGameStateSnapshot? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_game_state_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_api_simple_game_state(
      ApiSimpleGameState? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_api_simple_game_state(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
