// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Director choice view DTO for UI.
class ApiDirectorChoiceView {
  /// Choice identifier.
  final String id;

  /// Display label for the choice.
  final String label;

  const ApiDirectorChoiceView({
    required this.id,
    required this.label,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDirectorChoiceView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

/// Director event view DTO for UI display.
///
/// Represents a selected storylet with its available choices.
class ApiDirectorEventView {
  /// The storylet's unique identifier.
  final String storyletId;

  /// Display title for the event.
  final String title;

  /// Available choices for the player.
  final List<ApiDirectorChoiceView> choices;

  const ApiDirectorEventView({
    required this.storyletId,
    required this.title,
    required this.choices,
  });

  @override
  int get hashCode => storyletId.hashCode ^ title.hashCode ^ choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDirectorEventView &&
          runtimeType == other.runtimeType &&
          storyletId == other.storyletId &&
          title == other.title &&
          choices == other.choices;
}

/// Unified game state snapshot for Flutter UI.
///
/// Contains all necessary data for UI rendering in a single struct.
class ApiGameStateSnapshot {
  /// Current simulation tick.
  final BigInt currentTick;

  /// Player age in years.
  final int playerAgeYears;

  /// Player life stage.
  final String lifeStage;

  /// Player stats snapshot.
  final ApiStatsSnapshot stats;

  /// Player relationships snapshot.
  final ApiRelationshipSnapshot relationships;

  /// Current narrative heat.
  final double narrativeHeat;

  /// Heat level label.
  final String heatLevel;

  /// Heat trend (-1.0 to +1.0).
  final double heatTrend;

  /// Current event/storylet if any.
  final ApiDirectorEventView? currentEvent;

  /// Karma value.
  final double karma;

  /// Karma band label.
  final String karmaBand;

  /// Mood band label.
  final String moodBand;

  /// Life stage visibility info.
  final ApiLifeStageInfo lifeStageInfo;

  const ApiGameStateSnapshot({
    required this.currentTick,
    required this.playerAgeYears,
    required this.lifeStage,
    required this.stats,
    required this.relationships,
    required this.narrativeHeat,
    required this.heatLevel,
    required this.heatTrend,
    this.currentEvent,
    required this.karma,
    required this.karmaBand,
    required this.moodBand,
    required this.lifeStageInfo,
  });

  @override
  int get hashCode =>
      currentTick.hashCode ^
      playerAgeYears.hashCode ^
      lifeStage.hashCode ^
      stats.hashCode ^
      relationships.hashCode ^
      narrativeHeat.hashCode ^
      heatLevel.hashCode ^
      heatTrend.hashCode ^
      currentEvent.hashCode ^
      karma.hashCode ^
      karmaBand.hashCode ^
      moodBand.hashCode ^
      lifeStageInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiGameStateSnapshot &&
          runtimeType == other.runtimeType &&
          currentTick == other.currentTick &&
          playerAgeYears == other.playerAgeYears &&
          lifeStage == other.lifeStage &&
          stats == other.stats &&
          relationships == other.relationships &&
          narrativeHeat == other.narrativeHeat &&
          heatLevel == other.heatLevel &&
          heatTrend == other.heatTrend &&
          currentEvent == other.currentEvent &&
          karma == other.karma &&
          karmaBand == other.karmaBand &&
          moodBand == other.moodBand &&
          lifeStageInfo == other.lifeStageInfo;
}

/// Life stage information DTO with UI visibility flags.
///
/// Controls which stats are visible based on player's life stage.
class ApiLifeStageInfo {
  /// Current life stage label (e.g., "Child", "Teen", "Adult").
  final String lifeStage;

  /// Player's age in years.
  final int playerAgeYears;

  /// Whether to show wealth stat.
  final bool showWealth;

  /// Whether to show reputation stat.
  final bool showReputation;

  /// Whether to show wisdom stat.
  final bool showWisdom;

  /// Whether to show karma stat.
  final bool showKarma;

  const ApiLifeStageInfo({
    required this.lifeStage,
    required this.playerAgeYears,
    required this.showWealth,
    required this.showReputation,
    required this.showWisdom,
    required this.showKarma,
  });

  @override
  int get hashCode =>
      lifeStage.hashCode ^
      playerAgeYears.hashCode ^
      showWealth.hashCode ^
      showReputation.hashCode ^
      showWisdom.hashCode ^
      showKarma.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiLifeStageInfo &&
          runtimeType == other.runtimeType &&
          lifeStage == other.lifeStage &&
          playerAgeYears == other.playerAgeYears &&
          showWealth == other.showWealth &&
          showReputation == other.showReputation &&
          showWisdom == other.showWisdom &&
          showKarma == other.showKarma;
}

/// Simplified player configuration from Flutter character creation screen.
///
/// Minimal config struct that mirrors what the UI collects without
/// exposing internal complexity.
class ApiPlayerConfig {
  /// Player's chosen name.
  final String name;

  /// Optional pronouns (for future use).
  final String? pronouns;

  /// Character archetype (STORYTELLER, ANALYST, DREAMER, CHALLENGER).
  final String archetype;

  /// Difficulty setting (FORGIVING, BALANCED, HARSH).
  final String difficulty;

  /// Whether SFW mode is enabled.
  final bool sfwMode;

  const ApiPlayerConfig({
    required this.name,
    this.pronouns,
    required this.archetype,
    required this.difficulty,
    required this.sfwMode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      pronouns.hashCode ^
      archetype.hashCode ^
      difficulty.hashCode ^
      sfwMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPlayerConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          pronouns == other.pronouns &&
          archetype == other.archetype &&
          difficulty == other.difficulty &&
          sfwMode == other.sfwMode;
}

/// Full relationship DTO with bands and role labels for UI.
///
/// Includes both raw axis values and derived band labels.
class ApiRelationship {
  /// Actor (source) NPC ID.
  final PlatformInt64 actorId;

  /// Target NPC ID.
  final PlatformInt64 targetId;

  /// Affection axis value (-10.0 to +10.0).
  final double affection;

  /// Trust axis value (-10.0 to +10.0).
  final double trust;

  /// Attraction axis value (-10.0 to +10.0).
  final double attraction;

  /// Familiarity axis value (-10.0 to +10.0).
  final double familiarity;

  /// Resentment axis value (-10.0 to +10.0).
  final double resentment;

  /// Affection band label (e.g., "Warm", "Devoted").
  final String affectionBand;

  /// Trust band label.
  final String trustBand;

  /// Attraction band label.
  final String attractionBand;

  /// Resentment band label.
  final String resentmentBand;

  /// High-level summary for UI tags: "Friend", "Rival", "Crush", "Stranger", etc.
  final String roleLabel;

  const ApiRelationship({
    required this.actorId,
    required this.targetId,
    required this.affection,
    required this.trust,
    required this.attraction,
    required this.familiarity,
    required this.resentment,
    required this.affectionBand,
    required this.trustBand,
    required this.attractionBand,
    required this.resentmentBand,
    required this.roleLabel,
  });

  @override
  int get hashCode =>
      actorId.hashCode ^
      targetId.hashCode ^
      affection.hashCode ^
      trust.hashCode ^
      attraction.hashCode ^
      familiarity.hashCode ^
      resentment.hashCode ^
      affectionBand.hashCode ^
      trustBand.hashCode ^
      attractionBand.hashCode ^
      resentmentBand.hashCode ^
      roleLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRelationship &&
          runtimeType == other.runtimeType &&
          actorId == other.actorId &&
          targetId == other.targetId &&
          affection == other.affection &&
          trust == other.trust &&
          attraction == other.attraction &&
          familiarity == other.familiarity &&
          resentment == other.resentment &&
          affectionBand == other.affectionBand &&
          trustBand == other.trustBand &&
          attractionBand == other.attractionBand &&
          resentmentBand == other.resentmentBand &&
          roleLabel == other.roleLabel;
}

/// Snapshot of all player relationships for UI display.
class ApiRelationshipSnapshot {
  /// All player relationships with bands and role labels.
  final List<ApiRelationship> relationships;

  const ApiRelationshipSnapshot({
    required this.relationships,
  });

  @override
  int get hashCode => relationships.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRelationshipSnapshot &&
          runtimeType == other.runtimeType &&
          relationships == other.relationships;
}

/// Simplified game state snapshot for Flutter UI.
///
/// Thin wrapper around existing types, focused on what the UI needs
/// for day-to-day rendering without exposing full engine complexity.
class ApiSimpleGameState {
  /// Current in-game day (derived from ticks).
  final int currentDay;

  /// Current tick.
  final BigInt currentTick;

  /// Player age in years.
  final int playerAge;

  /// Player life stage label.
  final String lifeStage;

  /// Core player stats (health, energy, mood, etc.).
  final ApiStatsSnapshot stats;

  /// Current mood label.
  final String mood;

  /// Current karma value.
  final double karma;

  /// Current event if any (simplified view).
  final ApiDirectorEventView? currentEvent;

  /// Placeholder for relationships (minimal for now).
  final List<ApiSimpleRelationship> relationships;

  /// Placeholder for recent memories (minimal for now).
  final List<String> recentMemories;

  const ApiSimpleGameState({
    required this.currentDay,
    required this.currentTick,
    required this.playerAge,
    required this.lifeStage,
    required this.stats,
    required this.mood,
    required this.karma,
    this.currentEvent,
    required this.relationships,
    required this.recentMemories,
  });

  @override
  int get hashCode =>
      currentDay.hashCode ^
      currentTick.hashCode ^
      playerAge.hashCode ^
      lifeStage.hashCode ^
      stats.hashCode ^
      mood.hashCode ^
      karma.hashCode ^
      currentEvent.hashCode ^
      relationships.hashCode ^
      recentMemories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSimpleGameState &&
          runtimeType == other.runtimeType &&
          currentDay == other.currentDay &&
          currentTick == other.currentTick &&
          playerAge == other.playerAge &&
          lifeStage == other.lifeStage &&
          stats == other.stats &&
          mood == other.mood &&
          karma == other.karma &&
          currentEvent == other.currentEvent &&
          relationships == other.relationships &&
          recentMemories == other.recentMemories;
}

/// Simplified relationship view for UI.
class ApiSimpleRelationship {
  /// Target NPC ID.
  final PlatformInt64 npcId;

  /// NPC name (placeholder).
  final String name;

  /// Simplified relationship strength (-1.0 to 1.0).
  final double strength;

  const ApiSimpleRelationship({
    required this.npcId,
    required this.name,
    required this.strength,
  });

  @override
  int get hashCode => npcId.hashCode ^ name.hashCode ^ strength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSimpleRelationship &&
          runtimeType == other.runtimeType &&
          npcId == other.npcId &&
          name == other.name &&
          strength == other.strength;
}

/// Individual stat DTO with kind and value.
class ApiStat {
  /// Stat kind name (e.g., "Health", "Happiness", "Wealth").
  final String kind;

  /// Current value (typically 0.0-100.0).
  final double value;

  const ApiStat({
    required this.kind,
    required this.value,
  });

  @override
  int get hashCode => kind.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiStat &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value;
}

/// Player stats snapshot for serialization to Dart.
///
/// Contains all stat values and the current mood band label.
class ApiStatsSnapshot {
  /// All player stats with their current values.
  final List<ApiStat> stats;

  /// Current mood band label (e.g., "Happy", "Neutral", "Depressed").
  final String moodBand;

  const ApiStatsSnapshot({
    required this.stats,
    required this.moodBand,
  });

  @override
  int get hashCode => stats.hashCode ^ moodBand.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiStatsSnapshot &&
          runtimeType == other.runtimeType &&
          stats == other.stats &&
          moodBand == other.moodBand;
}
