// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 905038409;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__engine_choose_option_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_choose_option",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_storylet_id = <String>::sse_decode(&mut deserializer);
            let api_choice_id = <String>::sse_decode(&mut deserializer);
            let api_ticks = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::engine_choose_option(
                    api_storylet_id,
                    api_choice_id,
                    api_ticks,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine_new_game_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_new_game",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed = <u64>::sse_decode(&mut deserializer);
            let api_config = <crate::ApiPlayerConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::engine_new_game(api_seed, api_config))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine_step_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_step",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_ticks = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::engine_step(api_ticks))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine_tick_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_tick",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine_tick();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__engine_tick_many_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_tick_many",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_count = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::engine_tick_many(api_count);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_available_choices_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_available_choices",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_available_choices())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_current_storylet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_current_storylet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_current_storylet())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_game_state_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_game_state_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_game_state_snapshot())?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::ApiDirectorChoiceView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        return crate::ApiDirectorChoiceView {
            id: var_id,
            label: var_label,
        };
    }
}

impl SseDecode for crate::ApiDirectorEventView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_storyletId = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_choices = <Vec<crate::ApiDirectorChoiceView>>::sse_decode(deserializer);
        return crate::ApiDirectorEventView {
            storylet_id: var_storyletId,
            title: var_title,
            choices: var_choices,
        };
    }
}

impl SseDecode for crate::ApiGameStateSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentTick = <u64>::sse_decode(deserializer);
        let mut var_playerAgeYears = <u32>::sse_decode(deserializer);
        let mut var_lifeStage = <String>::sse_decode(deserializer);
        let mut var_stats = <crate::ApiStatsSnapshot>::sse_decode(deserializer);
        let mut var_relationships = <crate::ApiRelationshipSnapshot>::sse_decode(deserializer);
        let mut var_narrativeHeat = <f32>::sse_decode(deserializer);
        let mut var_heatLevel = <String>::sse_decode(deserializer);
        let mut var_heatTrend = <f32>::sse_decode(deserializer);
        let mut var_currentEvent = <Option<crate::ApiDirectorEventView>>::sse_decode(deserializer);
        let mut var_karma = <f32>::sse_decode(deserializer);
        let mut var_karmaBand = <String>::sse_decode(deserializer);
        let mut var_moodBand = <String>::sse_decode(deserializer);
        let mut var_lifeStageInfo = <crate::ApiLifeStageInfo>::sse_decode(deserializer);
        return crate::ApiGameStateSnapshot {
            current_tick: var_currentTick,
            player_age_years: var_playerAgeYears,
            life_stage: var_lifeStage,
            stats: var_stats,
            relationships: var_relationships,
            narrative_heat: var_narrativeHeat,
            heat_level: var_heatLevel,
            heat_trend: var_heatTrend,
            current_event: var_currentEvent,
            karma: var_karma,
            karma_band: var_karmaBand,
            mood_band: var_moodBand,
            life_stage_info: var_lifeStageInfo,
        };
    }
}

impl SseDecode for crate::ApiLifeStageInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lifeStage = <String>::sse_decode(deserializer);
        let mut var_playerAgeYears = <i32>::sse_decode(deserializer);
        let mut var_showWealth = <bool>::sse_decode(deserializer);
        let mut var_showReputation = <bool>::sse_decode(deserializer);
        let mut var_showWisdom = <bool>::sse_decode(deserializer);
        let mut var_showKarma = <bool>::sse_decode(deserializer);
        return crate::ApiLifeStageInfo {
            life_stage: var_lifeStage,
            player_age_years: var_playerAgeYears,
            show_wealth: var_showWealth,
            show_reputation: var_showReputation,
            show_wisdom: var_showWisdom,
            show_karma: var_showKarma,
        };
    }
}

impl SseDecode for crate::ApiPlayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_pronouns = <Option<String>>::sse_decode(deserializer);
        let mut var_archetype = <String>::sse_decode(deserializer);
        let mut var_difficulty = <String>::sse_decode(deserializer);
        let mut var_sfwMode = <bool>::sse_decode(deserializer);
        return crate::ApiPlayerConfig {
            name: var_name,
            pronouns: var_pronouns,
            archetype: var_archetype,
            difficulty: var_difficulty,
            sfw_mode: var_sfwMode,
        };
    }
}

impl SseDecode for crate::ApiRelationship {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_actorId = <i64>::sse_decode(deserializer);
        let mut var_targetId = <i64>::sse_decode(deserializer);
        let mut var_affection = <f32>::sse_decode(deserializer);
        let mut var_trust = <f32>::sse_decode(deserializer);
        let mut var_attraction = <f32>::sse_decode(deserializer);
        let mut var_familiarity = <f32>::sse_decode(deserializer);
        let mut var_resentment = <f32>::sse_decode(deserializer);
        let mut var_affectionBand = <String>::sse_decode(deserializer);
        let mut var_trustBand = <String>::sse_decode(deserializer);
        let mut var_attractionBand = <String>::sse_decode(deserializer);
        let mut var_resentmentBand = <String>::sse_decode(deserializer);
        let mut var_roleLabel = <String>::sse_decode(deserializer);
        return crate::ApiRelationship {
            actor_id: var_actorId,
            target_id: var_targetId,
            affection: var_affection,
            trust: var_trust,
            attraction: var_attraction,
            familiarity: var_familiarity,
            resentment: var_resentment,
            affection_band: var_affectionBand,
            trust_band: var_trustBand,
            attraction_band: var_attractionBand,
            resentment_band: var_resentmentBand,
            role_label: var_roleLabel,
        };
    }
}

impl SseDecode for crate::ApiRelationshipSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_relationships = <Vec<crate::ApiRelationship>>::sse_decode(deserializer);
        return crate::ApiRelationshipSnapshot {
            relationships: var_relationships,
        };
    }
}

impl SseDecode for crate::ApiSimpleGameState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_currentDay = <u32>::sse_decode(deserializer);
        let mut var_currentTick = <u64>::sse_decode(deserializer);
        let mut var_playerAge = <u32>::sse_decode(deserializer);
        let mut var_lifeStage = <String>::sse_decode(deserializer);
        let mut var_stats = <crate::ApiStatsSnapshot>::sse_decode(deserializer);
        let mut var_mood = <String>::sse_decode(deserializer);
        let mut var_karma = <f32>::sse_decode(deserializer);
        let mut var_currentEvent = <Option<crate::ApiDirectorEventView>>::sse_decode(deserializer);
        let mut var_relationships = <Vec<crate::ApiSimpleRelationship>>::sse_decode(deserializer);
        let mut var_recentMemories = <Vec<String>>::sse_decode(deserializer);
        return crate::ApiSimpleGameState {
            current_day: var_currentDay,
            current_tick: var_currentTick,
            player_age: var_playerAge,
            life_stage: var_lifeStage,
            stats: var_stats,
            mood: var_mood,
            karma: var_karma,
            current_event: var_currentEvent,
            relationships: var_relationships,
            recent_memories: var_recentMemories,
        };
    }
}

impl SseDecode for crate::ApiSimpleRelationship {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_npcId = <i64>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_strength = <f32>::sse_decode(deserializer);
        return crate::ApiSimpleRelationship {
            npc_id: var_npcId,
            name: var_name,
            strength: var_strength,
        };
    }
}

impl SseDecode for crate::ApiStat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_value = <f32>::sse_decode(deserializer);
        return crate::ApiStat {
            kind: var_kind,
            value: var_value,
        };
    }
}

impl SseDecode for crate::ApiStatsSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stats = <Vec<crate::ApiStat>>::sse_decode(deserializer);
        let mut var_moodBand = <String>::sse_decode(deserializer);
        return crate::ApiStatsSnapshot {
            stats: var_stats,
            mood_band: var_moodBand,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::ApiDirectorChoiceView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::ApiDirectorChoiceView>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::ApiRelationship> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::ApiRelationship>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::ApiSimpleRelationship> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::ApiSimpleRelationship>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::ApiStat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::ApiStat>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ApiDirectorEventView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ApiDirectorEventView>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ApiGameStateSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ApiGameStateSnapshot>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ApiSimpleGameState> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ApiSimpleGameState>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__engine_choose_option_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__engine_new_game_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__engine_step_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__engine_tick_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__engine_tick_many_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__get_available_choices_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__get_current_storylet_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__get_game_state_snapshot_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiDirectorChoiceView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiDirectorChoiceView {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiDirectorChoiceView>
    for crate::ApiDirectorChoiceView
{
    fn into_into_dart(self) -> crate::ApiDirectorChoiceView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiDirectorEventView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.storylet_id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.choices.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiDirectorEventView {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiDirectorEventView>
    for crate::ApiDirectorEventView
{
    fn into_into_dart(self) -> crate::ApiDirectorEventView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiGameStateSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_tick.into_into_dart().into_dart(),
            self.player_age_years.into_into_dart().into_dart(),
            self.life_stage.into_into_dart().into_dart(),
            self.stats.into_into_dart().into_dart(),
            self.relationships.into_into_dart().into_dart(),
            self.narrative_heat.into_into_dart().into_dart(),
            self.heat_level.into_into_dart().into_dart(),
            self.heat_trend.into_into_dart().into_dart(),
            self.current_event.into_into_dart().into_dart(),
            self.karma.into_into_dart().into_dart(),
            self.karma_band.into_into_dart().into_dart(),
            self.mood_band.into_into_dart().into_dart(),
            self.life_stage_info.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiGameStateSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiGameStateSnapshot>
    for crate::ApiGameStateSnapshot
{
    fn into_into_dart(self) -> crate::ApiGameStateSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiLifeStageInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.life_stage.into_into_dart().into_dart(),
            self.player_age_years.into_into_dart().into_dart(),
            self.show_wealth.into_into_dart().into_dart(),
            self.show_reputation.into_into_dart().into_dart(),
            self.show_wisdom.into_into_dart().into_dart(),
            self.show_karma.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiLifeStageInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiLifeStageInfo> for crate::ApiLifeStageInfo {
    fn into_into_dart(self) -> crate::ApiLifeStageInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiPlayerConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.pronouns.into_into_dart().into_dart(),
            self.archetype.into_into_dart().into_dart(),
            self.difficulty.into_into_dart().into_dart(),
            self.sfw_mode.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiPlayerConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiPlayerConfig> for crate::ApiPlayerConfig {
    fn into_into_dart(self) -> crate::ApiPlayerConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiRelationship {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.actor_id.into_into_dart().into_dart(),
            self.target_id.into_into_dart().into_dart(),
            self.affection.into_into_dart().into_dart(),
            self.trust.into_into_dart().into_dart(),
            self.attraction.into_into_dart().into_dart(),
            self.familiarity.into_into_dart().into_dart(),
            self.resentment.into_into_dart().into_dart(),
            self.affection_band.into_into_dart().into_dart(),
            self.trust_band.into_into_dart().into_dart(),
            self.attraction_band.into_into_dart().into_dart(),
            self.resentment_band.into_into_dart().into_dart(),
            self.role_label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiRelationship {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiRelationship> for crate::ApiRelationship {
    fn into_into_dart(self) -> crate::ApiRelationship {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiRelationshipSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.relationships.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ApiRelationshipSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiRelationshipSnapshot>
    for crate::ApiRelationshipSnapshot
{
    fn into_into_dart(self) -> crate::ApiRelationshipSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiSimpleGameState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.current_day.into_into_dart().into_dart(),
            self.current_tick.into_into_dart().into_dart(),
            self.player_age.into_into_dart().into_dart(),
            self.life_stage.into_into_dart().into_dart(),
            self.stats.into_into_dart().into_dart(),
            self.mood.into_into_dart().into_dart(),
            self.karma.into_into_dart().into_dart(),
            self.current_event.into_into_dart().into_dart(),
            self.relationships.into_into_dart().into_dart(),
            self.recent_memories.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiSimpleGameState {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiSimpleGameState> for crate::ApiSimpleGameState {
    fn into_into_dart(self) -> crate::ApiSimpleGameState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiSimpleRelationship {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.npc_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.strength.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiSimpleRelationship {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiSimpleRelationship>
    for crate::ApiSimpleRelationship
{
    fn into_into_dart(self) -> crate::ApiSimpleRelationship {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiStat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiStat {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiStat> for crate::ApiStat {
    fn into_into_dart(self) -> crate::ApiStat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ApiStatsSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stats.into_into_dart().into_dart(),
            self.mood_band.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ApiStatsSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::ApiStatsSnapshot> for crate::ApiStatsSnapshot {
    fn into_into_dart(self) -> crate::ApiStatsSnapshot {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::ApiDirectorChoiceView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
    }
}

impl SseEncode for crate::ApiDirectorEventView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.storylet_id, serializer);
        <String>::sse_encode(self.title, serializer);
        <Vec<crate::ApiDirectorChoiceView>>::sse_encode(self.choices, serializer);
    }
}

impl SseEncode for crate::ApiGameStateSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.current_tick, serializer);
        <u32>::sse_encode(self.player_age_years, serializer);
        <String>::sse_encode(self.life_stage, serializer);
        <crate::ApiStatsSnapshot>::sse_encode(self.stats, serializer);
        <crate::ApiRelationshipSnapshot>::sse_encode(self.relationships, serializer);
        <f32>::sse_encode(self.narrative_heat, serializer);
        <String>::sse_encode(self.heat_level, serializer);
        <f32>::sse_encode(self.heat_trend, serializer);
        <Option<crate::ApiDirectorEventView>>::sse_encode(self.current_event, serializer);
        <f32>::sse_encode(self.karma, serializer);
        <String>::sse_encode(self.karma_band, serializer);
        <String>::sse_encode(self.mood_band, serializer);
        <crate::ApiLifeStageInfo>::sse_encode(self.life_stage_info, serializer);
    }
}

impl SseEncode for crate::ApiLifeStageInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.life_stage, serializer);
        <i32>::sse_encode(self.player_age_years, serializer);
        <bool>::sse_encode(self.show_wealth, serializer);
        <bool>::sse_encode(self.show_reputation, serializer);
        <bool>::sse_encode(self.show_wisdom, serializer);
        <bool>::sse_encode(self.show_karma, serializer);
    }
}

impl SseEncode for crate::ApiPlayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.pronouns, serializer);
        <String>::sse_encode(self.archetype, serializer);
        <String>::sse_encode(self.difficulty, serializer);
        <bool>::sse_encode(self.sfw_mode, serializer);
    }
}

impl SseEncode for crate::ApiRelationship {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.actor_id, serializer);
        <i64>::sse_encode(self.target_id, serializer);
        <f32>::sse_encode(self.affection, serializer);
        <f32>::sse_encode(self.trust, serializer);
        <f32>::sse_encode(self.attraction, serializer);
        <f32>::sse_encode(self.familiarity, serializer);
        <f32>::sse_encode(self.resentment, serializer);
        <String>::sse_encode(self.affection_band, serializer);
        <String>::sse_encode(self.trust_band, serializer);
        <String>::sse_encode(self.attraction_band, serializer);
        <String>::sse_encode(self.resentment_band, serializer);
        <String>::sse_encode(self.role_label, serializer);
    }
}

impl SseEncode for crate::ApiRelationshipSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::ApiRelationship>>::sse_encode(self.relationships, serializer);
    }
}

impl SseEncode for crate::ApiSimpleGameState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.current_day, serializer);
        <u64>::sse_encode(self.current_tick, serializer);
        <u32>::sse_encode(self.player_age, serializer);
        <String>::sse_encode(self.life_stage, serializer);
        <crate::ApiStatsSnapshot>::sse_encode(self.stats, serializer);
        <String>::sse_encode(self.mood, serializer);
        <f32>::sse_encode(self.karma, serializer);
        <Option<crate::ApiDirectorEventView>>::sse_encode(self.current_event, serializer);
        <Vec<crate::ApiSimpleRelationship>>::sse_encode(self.relationships, serializer);
        <Vec<String>>::sse_encode(self.recent_memories, serializer);
    }
}

impl SseEncode for crate::ApiSimpleRelationship {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.npc_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <f32>::sse_encode(self.strength, serializer);
    }
}

impl SseEncode for crate::ApiStat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <f32>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::ApiStatsSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::ApiStat>>::sse_encode(self.stats, serializer);
        <String>::sse_encode(self.mood_band, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::ApiDirectorChoiceView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ApiDirectorChoiceView>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::ApiRelationship> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ApiRelationship>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::ApiSimpleRelationship> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ApiSimpleRelationship>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::ApiStat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ApiStat>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ApiDirectorEventView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ApiDirectorEventView>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ApiGameStateSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ApiGameStateSnapshot>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ApiSimpleGameState> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ApiSimpleGameState>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
